export {
	buildCompartmentBlock,
	escapeXmlAttr,
	escapeXmlContent,
	getCompartments,
	getSessionFacts,
	replaceAllCompartmentState,
	replaceAllCompartmentStateAndBumpDepth,
	type SessionFact,
} from "./compartment-storage";
export {
	clearCompressionDepth,
	getAverageCompressionDepth,
	getMaxCompressionDepth,
	incrementCompressionDepth,
} from "./compression-depth-storage";
export {
	AUTHORITY_DOMAINS,
	type AuthorityDomain,
	type AuthorityManagedMarker,
	type AuthorityModuleClient,
	type AuthorityState,
	type AuthorityStatus,
	applyMirrorPage,
	type ChangefeedPage,
	type ChangefeedRow,
	ensureContextStoreUuid,
	getAuthorityManagedMarker,
	getContextStoreUuid,
	getMirrorCursor,
	installAuthorityManagedMarker,
	listAuthorityManagedMarkers,
	type PrepareAuthorityArgs,
	prepareAuthority,
	pullAndApplyMirrorPage,
	reconcileAuthorityMarker,
	removeAuthorityManagedMarker,
} from "./context-authority";
export {
	normalizeStoredProjectPath,
	ProjectIdentityError,
	type ProjectIdentityErrorClass,
	resolveProjectIdentity,
	resolveProjectIdentityStrict,
	storedPathBelongsToIdentity,
} from "./memory/project-identity";
export {
	clearIndexedMessages,
	deleteIndexedMessage,
} from "./message-index";
export {
	computeProjectDocsHash,
	readProjectDocsCanonical,
} from "./project-docs-hash";
export {
	type CloneCompartmentRow,
	type CloneSessionStateFilter,
	type CloneTagRow,
	type CopySessionStateForCloneResult,
	copySessionStateForClone,
} from "./storage-clone";
export {
	applySqliteTuningPragmas,
	type ContextDatabase,
	closeDatabase,
	getDatabasePath,
	initializeDatabase,
	isDatabasePersisted,
	type OpenDatabaseOptions,
	openDatabase,
	runSqliteOptimize,
	setSqlitePragmaConfig,
} from "./storage-db";
export {
	beginSynapseBatchLedger,
	type EmbeddingMeasurementInput,
	type EmbeddingMeasurementRow,
	finishSynapseBatchLedger,
	listEmbeddingMeasurements,
	normalizedQueryHash,
	recordEmbeddingMeasurement,
	type SynapseBatchLedgerInput,
} from "./storage-embedding-measurements";
export {
	clearM0MutationsForSession,
	deleteM0Mutation,
	getM0Mutation,
	getM0MutationsAfterId,
	getM0MutationsBySession,
	getMaxM0MutationId,
	type M0MutationLogRow,
	type M0MutationType,
	queueM0Mutation,
	queueM0Mutation as appendM0Mutation,
} from "./storage-m0-mutation-log";
export {
	getMaxMemoryMutationId,
	getMaxMemoryMutationIdForProjects,
	getMemoryMutation,
	getMemoryMutationsForRender,
	getMemoryMutationsForRenderByProjects,
	type MemoryMutationLogRow,
	type MemoryMutationType,
	queueMemoryMutation,
} from "./storage-memory-mutation-log";
export {
	type AcquireWrapupResult,
	type AppendAutoSearchHintOutcome,
	type AutoSearchHintDecision,
	acquireWrapupInProgress,
	addProcessedImageStrippedIds,
	addStaleReduceStrippedIds,
	advanceToolReclaimWatermark,
	appendAutoSearchHintDecision,
	appendNoteNudgeAnchor,
	applyStrippedPlaceholderDelta,
	type Channel2NudgeState,
	casChannel2NudgeClaim,
	casChannel2NudgeState,
	claimChannel2NudgeState,
	clearCachedM0,
	clearCachedM0M1,
	clearDeferredExecutePendingIfMatches,
	clearDetectedContextLimit,
	clearEmergencyDrainLatch,
	clearEmergencyRecovery,
	clearHistorianDrainFailure,
	clearHistorianFailureState,
	clearPendingCompactionMarkerStateIf,
	clearPendingPiCompactionMarkerStateIf,
	clearPersistedNoteNudge,
	clearPersistedReasoningWatermark,
	clearSession,
	type DeferredExecutePayload,
	DRAIN_WINDOW_MS,
	deliverNoteNudgeAtomic,
	getAutoSearchHintDecisions,
	getChannel2NudgeClaim,
	getChannel2NudgeClaimedAt,
	getChannel2NudgeState,
	getHistorianFailureState,
	getLastNudgeLevel,
	getLastNudgeUndropped,
	getNoteLastReadAt,
	getNoteNudgeAnchors,
	getOrCreateSessionMeta,
	getOverflowState,
	getPendingCompactionMarkerState,
	getPendingPiCompactionMarkerState,
	getPersistedNoteNudge,
	getPersistedReasoningWatermark,
	getProcessedImageStrippedIds,
	getSessionsWithPendingMarker,
	getSessionsWithPendingPiMarker,
	getSessionWorkMetrics,
	getStaleReduceStrippedIds,
	getStrippedPlaceholderIds,
	getWrapupInProgressState,
	incrementHistorianFailure,
	isWrapupInProgress,
	loadPersistedUsage,
	loadProtectedTailMeta,
	markProtectedTailPolicyV3Seeded,
	markSessionCleanupPending,
	type PendingCompactionMarker,
	type PendingPiCompactionMarker,
	type PersistCachedM0Payload,
	type PersistedChannel1NudgeLevel,
	type PersistedOverflowState,
	type PersistedUsageState,
	type ProtectedTailDrainReservation,
	type ProtectedTailDrainReserveResult,
	type ProtectedTailMeta,
	type ProtectedTailSeedResult,
	peekDeferredExecutePending,
	persistCachedM0,
	protectedTailWindowBudget,
	pruneAutoSearchHintDecisions,
	pruneNoteNudgeAnchors,
	recordDetectedContextLimit,
	recordHistorianDrainFailure,
	recordOverflowDetected,
	recordProtectedTailNoEligibleHead,
	recordProtectedTailPublicationFloor,
	releaseWrapupInProgress,
	removeAutoSearchHintDecisionByMessageId,
	removeNoteNudgeAnchorByMessageId,
	removeStrippedPlaceholderId,
	reserveProtectedTailDrainTokens,
	resetLastNudgeCycle,
	resetLastNudgeCycleIfTailShrank,
	resetProtectedTailNoEligibleHead,
	retryPendingSessionCleanups,
	rollbackProtectedTailDrainReservation,
	setChannel2NudgeState,
	setDeferredExecutePendingIfAbsent,
	setLastNudgeLevel,
	setLastNudgeUndropped,
	setNoteLastReadAt,
	setPendingCompactionMarkerState,
	setPendingPiCompactionMarkerState,
	setPersistedReasoningWatermark,
	setSessionWorkMetrics,
	setStrippedPlaceholderIds,
	updateSessionMeta,
	updateWrapupInProgress,
	WRAPUP_IN_PROGRESS_TTL_MS,
	type WrapupInProgressState,
} from "./storage-meta";
export { bumpSessionFactsVersion } from "./storage-meta-shared";
export {
	addNote,
	deleteNote,
	dismissNote,
	getNotes,
	getPendingSmartNotes,
	getReadySmartNotes,
	getSessionNotes,
	getSmartNotes,
	markNoteChecked,
	markNoteReady,
	type Note,
	type NoteStatus,
	type NoteType,
	replaceAllSessionNotes,
	updateNote,
} from "./storage-notes";
export {
	clearPendingOps,
	getPendingOps,
	queuePendingOp,
	removePendingOp,
} from "./storage-ops";
export * from "./storage-primers";
export {
	bumpProjectMemoryEpoch,
	bumpProjectUserProfileVersion,
	deleteProjectState,
	ensureProjectState,
	GLOBAL_USER_PROFILE_PROJECT_PATH,
	getProjectState,
	type ProjectStateRow,
	setProjectState,
} from "./storage-project-state";
export {
	getSourceContents,
	replaceSourceContent,
	saveSourceContent,
} from "./storage-source";
export {
	getSubagentInvocations,
	getSubagentTotalsBySubagent,
	recordSubagentInvocation,
	type SubagentInvocationInput,
	type SubagentInvocationRow,
	type SubagentKind,
	type SubagentTotals,
} from "./storage-subagent-invocations";
export {
	type ActiveTagTokenAggregate,
	AGE_RECLAIM_MIN_TOKENS,
	type AgeReclaimToolTag,
	adoptFallbackTagMessageId,
	adoptPiFallbackMessageTag,
	adoptPiFallbackToolOwnerTag,
	deleteTagsByMessageId,
	deriveTagLoadFloor,
	findAdoptableFallbackTags,
	findPiFallbackToolOwnerTags,
	getActiveTagsBySession,
	getActiveTagTokenAggregate,
	getActiveTagTokenTotalsByMessage,
	getActiveToolTagsForAgeReclaim,
	getAllStatusTagTokenTotalsFlat,
	getMaxDroppedTagNumber,
	getMaxTagNumberBySession,
	getMinMessageTagNumberForRawId,
	getOldestActiveUnprotectedToolTags,
	getPersistedToolTagAccounting,
	getTagById,
	getTagsByNumbers,
	getTagsBySession,
	getTagsForPendingOperations,
	getTopNBySize,
	getTriggerTagTokenUpperBound,
	hasPiFallbackMessageTags,
	hasPiFallbackToolOwnerTags,
	insertTag,
	type MessageTokenTotal,
	type ToolReclaimHintTag,
	updateCavemanDepth,
	updateTagDropMode,
	updateTagMessageId,
	updateTagStatus,
} from "./storage-tags";
export {
	bumpEpochsForWorkspaceMemberSet,
	bumpEpochsForWorkspaceMembers,
	computeWorkspaceEpochFingerprint,
	type ExpandedWorkspaceIdentitySet,
	resolveStoredPathWorkspaceIdentity,
	resolveWorkspaceIdentityExpansion,
	resolveWorkspaceIdentitySet,
	sourceNameForMemory,
	storedPathBelongsToWorkspace,
	type WorkspaceIdentitySet,
} from "./workspaces";
